title: Viborg Brætspilsdag
description: Brætspil, rollespil og fællesskab i Viborg
lang: da

baseurl: ""
url: "https://viborgbraetspil.dk"

signup_url: "https://viborgbraetspil.dk/tilmelding/"

plugins:
  - jekyll-redirect-from
